// Code generated by mockery v2.9.4. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/p7chkn/go-musthave-diploma-tpl/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockJobStoreInterface is an autogenerated mock type for the JobStoreInterface type
type MockJobStoreInterface struct {
	mock.Mock
}

// AddJob provides a mock function with given fields: ctx, job
func (_m *MockJobStoreInterface) AddJob(ctx context.Context, job models.JobStoreRow) error {
	ret := _m.Called(ctx, job)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.JobStoreRow) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
